kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# No default CNI (kindnet) so we install Cilium manually, like on the real exam.
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"   # let Cilium replace kube-proxy (eBPF)
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
